{
  phases = {
    install = {
      cmds = [
        "npm install"
      ];
    };
    start = {
      cmd = "node server.js";
    };
  };

  # In your .nixpacks file or nix configuration
  buildInputs = [
    pkgs.python310  # Ensure this points to the Python 3.10 version
    pkgs.nodejs
    pkgs.npm
  ];
}
