[build]
  builder = "NIXPACKS"
  buildCommand = "npm install"

[deploy]
  startCommand = "node server.js"

[inputs]
  buildInputs = ["python310", "nodejs", "npm"]

[env]
  PIPENV_DEFAULT_PYTHON_VERSION = "3.10"  # Make sure Python 3.10 is being used
