[build]
  builder = "NIXPACKS"
  buildCommand = "npm install"

[deploy]
  startCommand = "node server.js"

[inputs]
  buildInputs = [
    pkgs.python310
    pkgs.nodejs
    pkgs.npm
  ]

[env]
  PIPENV_DEFAULT_PYTHON_VERSION = "3.10"  # Force Python 3.10 to be used
