{
  "build": {
    "cmds": [
      "npm install"
    ]
  },
  "deploy": {
    "cmd": "node server.js"
  },
  "env": {
    "NIXPACKS": {
      "buildInputs": [
        "python3.10",
        "nodejs",
        "npm"
      ]
    }
  }
}
