[build]
  builder = "NIXPACKS"
  buildCommand = "npm install"

[deploy]
  startCommand = "node server.js"

# In your .nixpacks.toml or Nixpack configuration
[env]
  PIPENV_DEFAULT_PYTHON_VERSION = "3.10"  # Set Python version to 3.10 for compatibility

[inputs]
  buildInputs = ["python310", "nodejs", "npm"]
